version: "3.2"
services:
    database:
        image: "postgres:10-alpine"
        ports:
            - 5432:5432
        environment: 
            POSTGRES_USER: hamzeh
            POSTGRES_PASSWORD: hamzeh1378
            PGPASSWORD: hamzeh1378
            POSTGRES_DB: maktab_final
            PGDATA: /db_data
        volumes: 
            - finalDbData3:/db_data
    cache:
        image: "memcached:alpine"
        ports:
            - 11211:11211 
    broker:
        image: "rabbitmq:alpine"
        ports:
            - 5672:5672                               
volumes:
    finalDbData3: